#!/usr/bin/env python3
"""
One-off: turn the textbook's Appendix A (pdftotext -layout output) into src/stats/tables-data.js.

The t, chi-squared and F tables are kept exactly as printed, misprints included, because the
grader should accept what a student reads off the page. The z, binomial and Poisson tables are
computed (src/stats/tables.js) and spot-checked against the page in scripts/stats-check.mjs.

  pdftotext -layout tables.pdf tables.txt && python3 scripts/extract_tables.py tables.txt
"""
import json, re, sys

lines = open(sys.argv[1], encoding='utf-8').read().split('\n')

def num(tok):
    return float('inf') if tok == '∞' else float(tok)

def rows(start_pat, stop_pat, skip=0):
    """Data rows (label then numbers) between the first line matching start_pat after `skip`."""
    out, on = [], False
    for i, ln in enumerate(lines):
        if i < skip:
            continue
        if not on and re.search(start_pat, ln):
            on = True
            continue
        if on and stop_pat and re.search(stop_pat, ln):
            break
        if not on:
            continue
        s = ln.strip()
        # 0.04 393 is the book's 0.0⁴393 = 0.0000393
        s = re.sub(r'\b0\.0(\d) (\d+)\b', lambda m: repr(float('0.' + '0' * int(m.group(1)) + m.group(2))), s)
        toks = s.split()
        if len(toks) < 3 or not re.fullmatch(r'\d+|∞', toks[0]):
            continue
        try:
            vals = [float(t) for t in toks[1:]]
        except ValueError:
            continue
        out.append((num(toks[0]), vals, i))
    return out

def header_after(pattern, skip=0):
    for i, ln in enumerate(lines):
        if i >= skip and re.search(pattern, ln):
            return i
    raise SystemExit(f'not found: {pattern}')

def table(first_title, cont_title, cols_a, cols_b, stop_a, stop_b):
    a0 = header_after(first_title)
    a = rows(r'^\s*v2?\s', stop_a, a0)
    b0 = header_after(cont_title, a[-1][2])
    b = rows(r'^\s*v2?\s', stop_b, b0)
    assert [r[0] for r in a] == [r[0] for r in b], 'row labels differ between halves'
    data = {}
    for (df, va, _), (_, vb, _) in zip(a, b):
        assert len(va) == len(cols_a) and len(vb) == len(cols_b), (df, va, vb)
        data[df] = va + vb
    return [r[0] for r in a], cols_a + cols_b, data

T_COLS_A = [0.40, 0.30, 0.20, 0.15, 0.10, 0.05, 0.025]
T_COLS_B = [0.02, 0.015, 0.01, 0.0075, 0.005, 0.0025, 0.0005]
t_rows, t_cols, t = table(r'Table A.4 Critical', r'Table A.4 \(continued\)', T_COLS_A, T_COLS_B, r'Table A.4', r'Table A.5')

C_COLS_A = [0.995, 0.99, 0.98, 0.975, 0.95, 0.90, 0.80, 0.75, 0.70, 0.50]
C_COLS_B = [0.30, 0.25, 0.20, 0.10, 0.05, 0.025, 0.02, 0.01, 0.005, 0.001]
c_rows, c_cols, c = table(r'Table A.5 Critical', r'Table A.5 \(continued\)', C_COLS_A, C_COLS_B, r'Table A.5', r'Table A.6')

F_V1_A = [1, 2, 3, 4, 5, 6, 7, 8, 9]
F_V1_B = [10, 12, 15, 20, 24, 30, 40, 60, 120, float('inf')]
def ftable(alpha_label, skip):
    a0 = header_after(r'f' + alpha_label, skip)
    a = rows(r'^\s*v2\s', r'Table A.6|Reproduced', a0)
    b0 = header_after(r'f' + alpha_label, a[-1][2])
    b = rows(r'^\s*v2\s', r'Table A.6', b0)
    assert [r[0] for r in a] == [r[0] for r in b]
    data = {}
    for (v2, va, _), (_, vb, _) in zip(a, b):
        assert len(va) == 9 and len(vb) == 10, (v2, va, vb)
        data[v2] = va + vb
    return [r[0] for r in a], data, b[-1][2]

f_rows, f05, end = ftable(r'0\.05', 0)
f_rows01, f01, _ = ftable(r'0\.01', end)
assert f_rows == f_rows01

def js(x):
    if x == float('inf'):
        return 'Infinity'
    return repr(x) if not float(x).is_integer() else str(int(x))

def grid(rows_, data):
    return '\n'.join(f'    [{", ".join(js(v) for v in data[r])}], // {js(r)}' for r in rows_)

out = f'''/**
 * Appendix A of the course textbook (Walpole, Myers, Myers & Ye), as printed. Generated by
 * scripts/extract_tables.py from the class's copy of the tables; do not edit by hand.
 *
 * Kept verbatim, misprints included, so a "table value" in a worked solution is the number on the
 * student's page. scripts/stats-check.mjs compares every entry with the exact value and lists the
 * entries that are off by more than rounding.
 *
 * t and chi-squared columns are upper-tail areas alpha; F columns are nu1 and rows nu2.
 */
export const T_TABLE = {{
  alphas: [{", ".join(js(a) for a in t_cols)}],
  dfs: [{", ".join(js(r) for r in t_rows)}],
  values: [
{grid(t_rows, t)}
  ],
}};

export const CHI2_TABLE = {{
  alphas: [{", ".join(js(a) for a in c_cols)}],
  dfs: [{", ".join(js(r) for r in c_rows)}],
  values: [
{grid(c_rows, c)}
  ],
}};

export const F_TABLE = {{
  alphas: [0.05, 0.01],
  v1s: [{", ".join(js(v) for v in F_V1_A + F_V1_B)}],
  v2s: [{", ".join(js(r) for r in f_rows)}],
  values: {{
    0.05: [
{grid(f_rows, f05).replace(chr(10) + '    ', chr(10) + '      ').replace('    [', '      [', 1)}
    ],
    0.01: [
{grid(f_rows, f01).replace(chr(10) + '    ', chr(10) + '      ').replace('    [', '      [', 1)}
    ],
  }},
}};
'''
open('src/stats/tables-data.js', 'w', encoding='utf-8').write(out)
print('t', len(t_rows), 'x', len(t_cols), '| chi2', len(c_rows), 'x', len(c_cols), '| F', len(f_rows), 'x 19 x 2')
