/**
 * Chapter 5, rewritten from the teacher's notes (Ch 5, pp. 58–71), laid out like FLUX's notes.
 * Example numbers are the notes'; the textbook's material (Walpole §5.2–5.5: multinomial,
 * hypergeometric, negative binomial, the Poisson approximation) is marked, and its examples are
 * lettered (5.A, 5.B, …).
 */
import { binomPmf, binomCdf, geomPmf, geomCdf, poisPmf, poisCdf, hyperPmf, choose, factorial } from '../stats/dist.js';

export default {
  ch: '5',
  title: 'Some discrete probability distributions',
  lede: 'Chapter 3 built distributions from scratch. In practice a handful of patterns cover most counting problems, and each comes with a ready-made formula for its probabilities, its mean and its variance. The skill this chapter teaches is recognising the pattern: a fixed number of independent trials (binomial), waiting for the first success (geometric), or events arriving at a steady rate (Poisson). The textbook adds sampling without replacement (hypergeometric) and a few relatives.',
  sections: [
    {
      id: '5.1',
      part: 'Counting successes in n trials',
      title: 'The binomial distribution',
      lab: 'dist',
      problems: ['c5.is-binomial', 'c5.binom-pmf', 'c5.binom-cdf', 'c5.binom-mean-var', 'c5.binom-table'],
      blocks: [
        ['p', 'A **Bernoulli trial** is a random experiment with exactly two outcomes, called success and failure (flipping a coin). A **binomial experiment** is:'],
        [
          'list',
          [
            'a FIXED number $n$ of identical Bernoulli trials;',
            'with the same probability of success $p$ on every trial (failure $1 - p$);',
            'and the trials are INDEPENDENT.',
          ],
        ],
        ['p', 'The **binomial random variable** $X$ counts the successes in the $n$ trials.'],
        [
          'ex',
          {
            n: '5.1',
            q: 'Is $X$ binomial? (a) Flip a coin 5 times; $X$ = number of heads. (b) Throw a die 10 times; $X$ = number of 5s or 6s. (c) A couple has children until their first girl; $X$ = number of children. (d) Test-fire a rifle 10 times while adjusting its scope; $X$ = number of bull’s-eyes. (e) From a box of 8 blue, 6 red and 3 white balls, pick 4; $X$ = number of red. (f) Peter tries the passwords he usually uses; he can fail 3 times, and a 4th wrong password locks the account. $X$ = number of tries.',
            a: [
              '(a) Yes: $n = 5$ independent flips, success = head, $p = 0.5$.',
              '(b) Yes: $n = 10$ independent throws, success = 5 or 6, $p = 2/6 = 1/3$.',
              '(c) No: there is no fixed $n$. (This one is geometric, §5.2.)',
              '(d) No: adjusting the scope between shots changes $p$, so the shots are not identical independent trials.',
              '(e) No: picking without replacement changes the chance of red after each draw, so the trials are not independent.',
              '(f) No: no fixed $n$, and no fixed success probability from try to try.',
            ],
            problem: 'c5.is-binomial',
            case: 0,
            checks: () => [['(b) p', 2 / 6, 1 / 3, 1e-12]],
          },
        ],
        ['key', String.raw`If $X$ is binomial with $n$ trials and success probability $p$: $P(X = x) = {}_nC_x\,p^x (1 - p)^{n - x}$, for $x = 0, 1, 2, \ldots, n$.`],
        ['why', String.raw`$p^x(1-p)^{n-x}$ is the probability of one particular order of $x$ successes and $n - x$ failures (independent trials, so multiply); $_nC_x$ counts the orders, which are mutually exclusive, so add. Ex 3.3 was this with $n = 4$, $p = 1/2$.`],
        [
          'ex',
          {
            n: '5.2',
            q: '15% of people in the U.S. have blood type O-negative. In a simple random sample of 4 people, let $X$ be the number with O-negative. Make the probability distribution table.',
            a: [
              'Each person is a trial (O-negative = success), $n = 4$, independent: $X$ is binomial with $n = 4$, $p = 0.15$.',
              String.raw`$P(X = 0) = {}_4C_0 (0.15)^0 (0.85)^4 = 0.5220$; $P(X = 1) = {}_4C_1 (0.15)^1 (0.85)^3 = 0.3685$.`,
              'Likewise $P(X = 2) = 0.0975$, $P(X = 3) = 0.0115$, $P(X = 4) = 0.0005$.',
            ],
            answer: 'x: 0, 1, 2, 3, 4 with f(x) = 0.5220, 0.3685, 0.0975, 0.0115, 0.0005.',
            problem: 'c5.binom-pmf',
            case: 0,
            checks: () => [[0.522, 0], [0.3685, 1], [0.0975, 2], [0.0115, 3], [0.0005, 4]].map(([v, x]) => [`f(${x})`, binomPmf(x, 4, 0.15), v, 5e-5]),
          },
        ],
        [
          'ex',
          {
            n: '5.3',
            q: '65% of adult Americans favor the death penalty for murder. In a random sample of 15, find the probability that (a) exactly 10 favor it; (b) no more than 6 favor it.',
            a: ['$X$ = number in favor: binomial, $n = 15$, $p = 0.65$.', '(a) $P(X = 10) = $ binompdf(15, 0.65, 10) $= 0.2123$.', '(b) "No more than 6" is $X \\le 6$: $P(X \\le 6) = $ binomcdf(15, 0.65, 6) $= 0.0422$.'],
            answer: '(a) 0.2123, (b) 0.0422.',
            problem: 'c5.binom-pmf',
            case: 1,
            show: 'dist:favor',
            checks: () => [
              ['(a)', binomPmf(10, 15, 0.65), 0.2123, 5e-5],
              ['(b)', binomCdf(6, 15, 0.65), 0.0422, 5e-5],
            ],
          },
        ],
        ['ti', ['2nd VARS (DISTR) ▸ A:binompdf( for $P(X = x)$: trials $n$, $p$, x value.', '2nd VARS ▸ B:binomcdf( for $P(X \\le x)$, same inputs.', 'Everything else is built from these two (below).']],
        [
          'ex',
          {
            n: '5.4',
            q: '41% of U.S. households are wireless-only. In a random sample of 20 households, find the probability that the number of wireless-only households is (a) exactly 5; (b) fewer than 3; (c) no more than 3; (d) at least 3; (e) between 5 and 7, inclusive.',
            a: [
              '$X$ is binomial, $n = 20$, $p = 0.41$.',
              '(a) $P(X = 5) = $ binompdf(20, 0.41, 5) $= 0.0656$.',
              '(b) Fewer than 3 is 0, 1, 2: $P(X < 3) = P(X \\le 2) = $ binomcdf(20, 0.41, 2) $= 0.0028$.',
              '(c) $P(X \\le 3) = $ binomcdf(20, 0.41, 3) $= 0.0128$.',
              '(d) At least 3 is the complement of 0, 1, 2: $P(X \\ge 3) = 1 - P(X \\le 2) = 1 - 0.0028 = 0.9972$.',
              '(e) $P(5 \\le X \\le 7) = P(X \\le 7) - P(X \\le 4) = 0.3381$. (Or add binompdf for 5, 6 and 7.)',
            ],
            answer: '(a) 0.0656 (b) 0.0028 (c) 0.0128 (d) 0.9972 (e) 0.3381.',
            problem: 'c5.binom-cdf',
            case: 1,
            show: 'dist:wireless',
            checks: () => [
              ['(a)', binomPmf(5, 20, 0.41), 0.0656, 5e-5],
              ['(b)', binomCdf(2, 20, 0.41), 0.0028, 5e-5],
              ['(c)', binomCdf(3, 20, 0.41), 0.0128, 5e-5],
              ['(d)', 1 - binomCdf(2, 20, 0.41), 0.9972, 5e-5],
              ['(e)', binomCdf(7, 20, 0.41) - binomCdf(4, 20, 0.41), 0.3381, 5e-5],
            ],
          },
        ],
        [
          'table',
          {
            head: ['In words', 'Event', 'On the TI-84'],
            rows: [
              ['exactly $a$', '$X = a$', 'binompdf($n, p, a$)'],
              ['at most $a$, no more than $a$', '$X \\le a$', 'binomcdf($n, p, a$)'],
              ['fewer than $a$', '$X \\le a - 1$', 'binomcdf($n, p, a - 1$)'],
              ['at least $a$', '$X \\ge a$', '1 − binomcdf($n, p, a - 1$)'],
              ['more than $a$', '$X \\ge a + 1$', '1 − binomcdf($n, p, a$)'],
              ['$a$ to $b$ inclusive', '$a \\le X \\le b$', 'binomcdf($n, p, b$) − binomcdf($n, p, a - 1$)'],
            ],
            note: 'For a discrete $X$ the endpoints matter: write out which whole numbers the event includes before reaching for the calculator.',
          },
        ],
        ['key', String.raw`Binomial mean and variance: $\mu = np$, $\sigma^2 = np(1 - p)$. (Only for the binomial.)`],
        ['why', String.raw`Write $X = X_1 + \cdots + X_n$, where $X_i$ is 1 if trial $i$ succeeds and 0 if not. Each $X_i$ has mean $p$ and variance $E(X_i^2) - p^2 = p - p^2 = p(1 - p)$. The trials are independent, so by §4.3 the means add to $np$ and the variances add to $np(1 - p)$.`, 'Derivation'],
        [
          'ex',
          {
            n: '5.5',
            q: 'For the 20 households of Example 5.4, find the mean and standard deviation of the number of wireless-only households.',
            a: [String.raw`$\mu = np = 20(0.41) = 8.2$ households.`, String.raw`$\sigma^2 = np(1 - p) = 20(0.41)(0.59) = 4.838$, so $\sigma = \sqrt{4.838} = 2.2$ households.`],
            answer: 'μ = 8.2, σ = 2.2 households.',
            problem: 'c5.binom-mean-var',
            case: 0,
            checks: () => [
              ['μ', 20 * 0.41, 8.2, 1e-12],
              ['σ²', 20 * 0.41 * 0.59, 4.838, 1e-9],
              ['σ', Math.sqrt(20 * 0.41 * 0.59), 2.2, 5e-3],
            ],
          },
        ],
        ['p', 'Read the mean as the center of the histogram: in 20 households, about 8 are wireless-only, give or take about 2. The values from 5 to 7 in Ex 5.4(e) sit just below that center.'],
        [
          'book',
          'Walpole §5.2',
          [
            ['p', String.raw`The binomial has two outcomes per trial. With $k$ outcomes per trial, of probabilities $p_1, \ldots, p_k$ (adding to 1), the counts $X_1, \ldots, X_k$ of each outcome in $n$ independent trials have the **multinomial distribution**:`],
            ['p', String.raw`$$f(x_1, \ldots, x_k) = \frac{n!}{x_1!\,x_2!\cdots x_k!}\,p_1^{x_1} p_2^{x_2} \cdots p_k^{x_k}, \qquad x_1 + \cdots + x_k = n.$$`],
            ['p', 'The fraction counts the orders (the like-objects count of §2.4), and the product is the probability of any one order.'],
            [
              'ex',
              {
                n: '5.A',
                title: 'coffee sizes',
                q: 'At a coffee kiosk, 30% of orders are small, 50% medium and 20% large, independently. Find the probability that of the next 10 orders, 3 are small, 5 medium and 2 large.',
                a: [String.raw`$\dfrac{10!}{3!\,5!\,2!} = 2520$ orders of the sizes.`, String.raw`$P = 2520\,(0.3)^3 (0.5)^5 (0.2)^2 = 2520(0.027)(0.03125)(0.04) = 0.0851$.`],
                answer: '0.0851.',
                checks: () => [
                  ['count', factorial(10) / (factorial(3) * factorial(5) * factorial(2)), 2520, 0],
                  ['P', 2520 * 0.3 ** 3 * 0.5 ** 5 * 0.2 ** 2, 0.0851, 5e-5],
                ],
              },
            ],
          ],
        ],
        ['bridge', 'The binomial fixes the number of trials and counts the successes. Turn that around, fix the number of successes (one) and count the trials, and the distribution is geometric.'],
      ],
    },
    {
      id: '5.2',
      part: 'Waiting for a success',
      title: 'The geometric distribution',
      lab: 'dist',
      problems: ['c5.geometric'],
      blocks: [
        ['p', 'A **geometric experiment** repeats independent, identical Bernoulli trials (success probability $p$ each time) until the FIRST success. The geometric random variable $X$ is the number of the trial on which it happens.'],
        ['key', String.raw`$P(X = x) = p(1 - p)^{x - 1}$, for $x = 1, 2, 3, \ldots$ Mean $\mu = \dfrac{1}{p}$, variance $\sigma^2 = \dfrac{1 - p}{p^2}$.`],
        ['why', 'The first success on trial $x$ means $x - 1$ failures first, then a success: $(1-p)^{x-1} p$.'],
        [
          'ex',
          {
            n: '5.6',
            q: 'On average 1 in every 100 items made is defective. (a) What is the probability that the 5th item inspected is the first defective? (b) What is the probability the first defective is found within 5 inspections?',
            a: [
              '$X$ = number of items inspected to find the first defective: geometric with $p = 0.01$.',
              String.raw`(a) $P(X = 5) = 0.01(0.99)^4 = $ geometpdf(0.01, 5) $= 0.0096$.`,
              String.raw`(b) $P(X \le 5) = $ geometcdf(0.01, 5) $= 0.0490$.`,
            ],
            answer: '(a) 0.0096 (b) 0.0490.',
            problem: 'c5.geometric',
            case: 0,
            show: 'dist:items',
            checks: () => [
              ['(a)', geomPmf(5, 0.01), 0.0096, 5e-5],
              ['(b)', geomCdf(5, 0.01), 0.049, 5e-5],
            ],
          },
        ],
        ['ti', ['2nd VARS ▸ F:geometpdf( with $p$ and x value: $P(X = x)$.', '2nd VARS ▸ G:geometcdf(: $P(X \\le x)$. (Letters vary by model; scroll the DISTR menu.)']],
        [
          'ex',
          {
            n: '5.7',
            q: 'In the same process, how many inspections does it take, on average, to find the first defective? Find the standard deviation too.',
            a: [String.raw`$\mu = 1/p = 1/0.01 = 100$ items.`, String.raw`$\sigma^2 = (1 - p)/p^2 = 0.99/0.0001 = 9900$, so $\sigma = \sqrt{9900} = 99.5$ items.`],
            answer: 'μ = 100 items, σ = 99.5 items.',
            problem: 'c5.geometric',
            case: 0,
            checks: () => [
              ['μ', 1 / 0.01, 100, 1e-9],
              ['σ²', 0.99 / 0.0001, 9900, 1e-6],
              ['σ', Math.sqrt(9900), 99.5, 5e-3],
            ],
          },
        ],
        ['p', String.raw`The mean $1/p$ matches intuition: if 1 item in 100 is defective, you expect to look at about 100. The standard deviation is almost as large, because the wait is very skewed: usually shorter than 100, occasionally much longer.`],
        ['key', String.raw`"Within $x$ trials" has a shortcut: the first success is later than trial $x$ only if the first $x$ trials all fail, so $P(X \le x) = 1 - (1 - p)^x$. In Ex 5.6(b), $1 - 0.99^5 = 0.0490$.`],
        [
          'book',
          'Walpole §5.4',
          [
            ['p', String.raw`Wait instead for the $k$th success. The trial $X$ on which it happens has the **negative binomial distribution**: the first $x - 1$ trials must hold exactly $k - 1$ successes (a binomial count), and trial $x$ must be a success.`],
            ['p', String.raw`$$P(X = x) = {}_{x-1}C_{k-1}\;p^k (1 - p)^{x - k}, \qquad x = k, k + 1, \ldots$$`],
            ['p', String.raw`With $k = 1$ it is the geometric distribution. Its mean is $k/p$: $k$ geometric waits, one after another.`],
            [
              'ex',
              {
                n: '5.B',
                title: 'free throws',
                q: 'A player makes 70% of free throws, independently. What is the probability that her 3rd make comes on her 5th attempt?',
                a: [String.raw`The first 4 attempts hold exactly 2 makes, and the 5th is a make: $_4C_2\,(0.7)^3(0.3)^2 = 6(0.343)(0.09)$.`],
                answer: '0.1852.',
                checks: () => [
                  ['4C2', choose(4, 2), 6, 0],
                  ['P', choose(4, 2) * 0.7 ** 3 * 0.3 ** 2, 0.1852, 5e-5],
                ],
              },
            ],
          ],
        ],
        ['bridge', 'Binomial and geometric both count trials. The Poisson counts events that have no trials at all: arrivals, accidents, flaws, happening at some average rate over time or space.'],
      ],
    },
    {
      id: '5.3',
      part: 'Counting rare events',
      title: 'The Poisson distribution',
      lab: 'dist',
      problems: ['c5.poisson-basics', 'c5.poisson-rate', 'c5.poisson-table', 'c5.which-distribution'],
      blocks: [
        ['p', 'The **Poisson distribution** counts events in a fixed interval of time or region of space, when the events are rare, random and independent: fatalities per 100 million miles, calls per hour, flaws per square meter.'],
        ['key', String.raw`$P(X = x) = \dfrac{e^{-\lambda}\lambda^x}{x!}$, for $x = 0, 1, 2, \ldots$, where $\lambda$ is the average number of events in the interval. Mean and variance are both $\lambda$.`],
        ['warn', String.raw`$\lambda$ must match the interval asked about. If deaths occur at 1.5 per 100 million miles, then over 200 million miles $\lambda = 3$, and over 50 million miles $\lambda = 0.75$.`],
        [
          'ex',
          {
            n: '5.8',
            q: 'Traffic fatalities occur at a rate of 1.5 per 100 million miles, following a Poisson distribution. Find the probability of (a) no deaths in 100 million miles; (b) at least one; (c) more than one. (d) Give the mean, variance and standard deviation. (e) Find the probability of exactly 2 deaths in 200 million miles; (f) fewer than 2 deaths in 50 million miles.',
            a: [
              '$X$ = deaths in 100 million miles: Poisson with $\\lambda = 1.5$.',
              String.raw`(a) $P(X = 0) = \dfrac{e^{-1.5}(1.5)^0}{0!} = $ poissonpdf(1.5, 0) $= 0.2231$.`,
              String.raw`(b) $P(X \ge 1) = 1 - P(X = 0) = 1 - 0.2231 = 0.7769$.`,
              String.raw`(c) $P(X > 1) = 1 - P(X \le 1) = 1 - $ poissoncdf(1.5, 1) $= 0.4422$.`,
              String.raw`(d) $\mu = 1.5$, $\sigma^2 = 1.5$, $\sigma = \sqrt{1.5} = 1.225$.`,
              String.raw`(e) $Y$ = deaths in 200 million miles has $\lambda = 3$: $P(Y = 2) = $ poissonpdf(3, 2) $= 0.2240$.`,
              String.raw`(f) $Z$ = deaths in 50 million miles has $\lambda = 0.75$: $P(Z < 2) = P(Z \le 1) = $ poissoncdf(0.75, 1) $= 0.8266$.`,
            ],
            answer: '(a) 0.2231 (b) 0.7769 (c) 0.4422 (d) 1.5, 1.5, 1.225 (e) 0.2240 (f) 0.8266.',
            problem: 'c5.poisson-basics',
            case: 0,
            show: 'dist:deaths',
            checks: () => [
              ['(a)', poisPmf(0, 1.5), 0.2231, 5e-5],
              ['(b)', 1 - poisPmf(0, 1.5), 0.7769, 5e-5],
              ['(c)', 1 - poisCdf(1, 1.5), 0.4422, 5e-5],
              ['(d) σ', Math.sqrt(1.5), 1.225, 5e-4],
              ['(e)', poisPmf(2, 3), 0.224, 5e-5],
              ['(f)', poisCdf(1, 0.75), 0.8266, 5e-5],
            ],
          },
        ],
        ['fix', 'In part (b) the notes compute 1 − 0.2231 = 0.7669. The subtraction gives 0.7769.'],
        ['ti', ['2nd VARS ▸ poissonpdf($\\lambda$, x) for $P(X = x)$; poissoncdf($\\lambda$, x) for $P(X \\le x)$.']],
        [
          'table',
          {
            head: ['', 'Binomial', 'Geometric', 'Poisson'],
            rows: [
              ['$X$ counts', 'successes in $n$ trials', 'trials to the first success', 'events in an interval'],
              ['values', '$0, 1, \\ldots, n$', '$1, 2, 3, \\ldots$', '$0, 1, 2, \\ldots$'],
              ['mean', '$np$', '$1/p$', '$\\lambda$'],
              ['variance', '$np(1-p)$', '$(1-p)/p^2$', '$\\lambda$'],
            ],
            note: 'Which one? A fixed number of trials: binomial. Trials until something first happens: geometric. A rate per unit of time or space, with no fixed number of trials: Poisson.',
          },
        ],
        [
          'book',
          'Walpole §5.5',
          [
            ['p', String.raw`The Poisson is also the limit of the binomial when $n$ is large and $p$ is small: many trials, each very unlikely to succeed. Then $b(x; n, p) \approx p(x; \mu)$ with $\mu = np$. The approximation is good when $n$ is large and $np$ is moderate; a rule of thumb often quoted is $n \ge 20$ with $p \le 0.05$.`],
            [
              'ex',
              {
                n: '5.C',
                title: 'rare defects',
                q: 'One item in 1000 is defective. In a shipment of 3000, what is the probability of at most 2 defectives? Compare the exact binomial with the Poisson approximation.',
                a: [
                  String.raw`Exact: $X$ is binomial, $n = 3000$, $p = 0.001$: binomcdf(3000, 0.001, 2) $= 0.4231$.`,
                  String.raw`Approximate: $\mu = np = 3$, and $P(X \le 2) \approx e^{-3}\left(1 + 3 + \tfrac{3^2}{2}\right) = 8.5\,e^{-3} = 0.4232$.`,
                ],
                answer: 'Both give 0.423, agreeing to three decimals.',
                checks: () => [
                  ['exact', binomCdf(2, 3000, 0.001), 0.4231, 5e-5],
                  ['Poisson', poisCdf(2, 3), 0.4232, 5e-5],
                  ['by hand', 8.5 * Math.exp(-3), 0.4232, 5e-5],
                ],
              },
            ],
          ],
        ],
        ['bridge', 'All three distributions so far assume independent trials or events. Drawing from a small batch without putting items back breaks that, which is why Ex 5.1(e) was not binomial. The textbook has a distribution for exactly that case.'],
      ],
    },
    {
      id: '5.4',
      part: 'Sampling without replacement',
      title: 'The hypergeometric distribution',
      source: 'Walpole §5.3',
      lab: 'dist',
      blocks: [
        ['p', String.raw`A lot of $N$ items contains $k$ "successes" (defectives, red balls) and $N - k$ failures. Draw $n$ of them WITHOUT replacement. The number of successes drawn, $X$, is **hypergeometric**. It is not binomial, because each draw changes what is left.`],
        ['key', String.raw`$P(X = x) = \dfrac{{}_kC_x \cdot {}_{N-k}C_{n-x}}{{}_NC_n}$, for $\max(0,\ n - (N - k)) \le x \le \min(n, k)$.`],
        ['why', 'Every group of $n$ items is equally likely: ${}_NC_n$ of them. The ones with exactly $x$ successes pick $x$ of the $k$ successes and $n - x$ of the $N - k$ failures: the multiplication rule of §2.4.'],
        ['key', String.raw`Mean $\mu = n\,\dfrac{k}{N}$, variance $\sigma^2 = \dfrac{N - n}{N - 1} \cdot n \cdot \dfrac{k}{N}\left(1 - \dfrac{k}{N}\right)$.`],
        ['p', String.raw`The mean is the binomial’s, with $p = k/N$. The variance is the binomial’s times $\frac{N - n}{N - 1}$, the **finite population correction**: less than 1, because drawing without replacement leaves less to chance (draw all $N$ and there is no randomness left at all).`],
        [
          'ex',
          {
            n: '5.D',
            title: 'a lot of 20',
            q: 'A lot of 20 items contains 4 defectives. An inspector draws 5 at random without replacement. Find (a) the probability of exactly 2 defectives; (b) the probability of at least one; (c) the mean and variance of the number of defectives drawn.',
            a: [
              String.raw`$N = 20$, $k = 4$, $n = 5$.`,
              String.raw`(a) $P(X = 2) = \dfrac{{}_4C_2 \cdot {}_{16}C_3}{{}_{20}C_5} = \dfrac{6 \cdot 560}{15{,}504} = \dfrac{3360}{15{,}504} = 0.2167$.`,
              String.raw`(b) $P(X \ge 1) = 1 - P(X = 0) = 1 - \dfrac{{}_{16}C_5}{{}_{20}C_5} = 1 - \dfrac{4368}{15{,}504} = 0.7183$.`,
              String.raw`(c) $\mu = 5 \cdot \tfrac{4}{20} = 1$; $\sigma^2 = \tfrac{15}{19} \cdot 5 \cdot 0.2 \cdot 0.8 = 0.632$.`,
            ],
            answer: '(a) 0.2167 (b) 0.7183 (c) μ = 1, σ² = 0.632. Treated as binomial, (a) would be 0.2048.',
            show: 'dist:lot',
            checks: () => [
              ['4C2', choose(4, 2), 6, 0],
              ['16C3', choose(16, 3), 560, 0],
              ['20C5', choose(20, 5), 15504, 0],
              ['(a)', hyperPmf(2, 20, 5, 4), 0.2167, 5e-5],
              ['16C5', choose(16, 5), 4368, 0],
              ['(b)', 1 - hyperPmf(0, 20, 5, 4), 0.7183, 5e-5],
              ['μ', (5 * 4) / 20, 1, 0],
              ['σ²', (15 / 19) * 5 * 0.2 * 0.8, 0.632, 5e-4],
              ['binomial instead', binomPmf(2, 5, 0.2), 0.2048, 5e-5],
            ],
          },
        ],
        ['p', String.raw`Ex 5.1(e) is the same pattern: 17 balls, 6 red, pick 4, so $X$ = number of red is hypergeometric with $N = 17$, $k = 6$, $n = 4$.`],
        ['key', String.raw`When the sample is a small part of the lot ($n/N \le 0.05$), removing a few items hardly changes the proportion, and the binomial with $p = k/N$ is a good approximation.`],
        ['ti', ['The TI-84 has no hypergeometric menu item. Use MATH ▸ PROB ▸ 3:nCr for the three combinations, as in (a).']],
        ['bridge', 'Every variable in this chapter was a count. Chapter 6 turns to measurements, continuous variables, and to the most important distribution in statistics: the normal.'],
      ],
    },
  ],
  formulas: [
    ['Binomial', String.raw`$P(X = x) = {}_nC_x\,p^x(1-p)^{n-x}$, $\;\mu = np$, $\;\sigma^2 = np(1-p)$`],
    ['Geometric', String.raw`$P(X = x) = p(1-p)^{x-1}$, $\;\mu = 1/p$, $\;\sigma^2 = (1-p)/p^2$`],
    ['Geometric, within $x$ trials', String.raw`$P(X \le x) = 1 - (1-p)^x$`],
    ['Poisson', String.raw`$P(X = x) = \dfrac{e^{-\lambda}\lambda^x}{x!}$, $\;\mu = \sigma^2 = \lambda$`],
    ['Multinomial', String.raw`$\dfrac{n!}{x_1!\cdots x_k!}\,p_1^{x_1}\cdots p_k^{x_k}$`, 'Walpole §5.2'],
    ['Negative binomial', String.raw`$P(X = x) = {}_{x-1}C_{k-1}\,p^k(1-p)^{x-k}$`, 'Walpole §5.4'],
    ['Poisson approximation', String.raw`$b(x; n, p) \approx p(x; np)$ for large $n$, small $p$`, 'Walpole §5.5'],
    ['Hypergeometric', String.raw`$P(X = x) = \dfrac{{}_kC_x\,{}_{N-k}C_{n-x}}{{}_NC_n}$, $\;\mu = nk/N$`, 'Walpole §5.3'],
  ],
};
